#!/usr/bin/env bash
# scorecard.sh — run the validation corpus, compute precision/recall, regenerate docs/scorecard.md.
#   (default)     regenerate docs/scorecard.md from the synthetic corpus
#   --check       fail if docs/scorecard.md is stale or synthetic precision < floor
#   --real        clone + score the pinned real-app panel (network; non-blocking CI)
#   --selftest    print metric math on a fixed toy corpus (for tests)
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCAN="$ROOT/skills/appstore-precheck/scripts/scan.sh"
SYN="$ROOT/corpus/synthetic/labels.json"
CARD="$ROOT/docs/scorecard.md"
FLOOR="0.80"

# _metrics <tp> <fp> <fn> -> "precision=<p> recall=<r>" (2dp, guard div0)
_metrics() {
  awk -v tp="$1" -v fp="$2" -v fn="$3" 'BEGIN{
    p = (tp+fp>0)? tp/(tp+fp) : 1;
    r = (tp+fn>0)? tp/(tp+fn) : 1;
    printf "precision=%.2f recall=%.2f", p, r;
  }'
}

if [[ "${1:-}" == "--selftest" ]]; then
  # toy: tp=2 fp=0 fn=2 -> precision 1.00, recall 0.50
  _metrics 2 0 2; echo; exit 0
fi

# run the synthetic corpus -> aggregate tp/fp/fn.
#
# IMPORTANT: each fixture is copied to a fresh mktemp dir OUTSIDE this git repo
# before scan.sh runs on it (mirroring tests/run.sh). scan.sh resolves its own
# ROOT via `git rev-parse --show-toplevel` and then `cd`s there (scan.sh:12-13);
# tests/fixtures/<name>/ lives *inside* the appstore-precheck repo, so invoking
# scan.sh with cwd = tests/fixtures/<name> makes it `cd` back out to the
# appstore-precheck repo root and scan an essentially random sibling fixture's
# layout instead of the intended one. Copying out first is what makes each
# fixture measure itself.
run_synthetic() {
  local fx name fired want absent rid tp=0 fp=0 fn=0 tmp
  for fx in "$ROOT"/tests/fixtures/*/; do
    name="$(basename "$fx")"
    jq -e --arg n "$name" 'has($n)' "$SYN" >/dev/null 2>&1 || continue
    tmp="$(mktemp -d)"
    cp -R "$fx." "$tmp/"
    fired="$(cd "$tmp" && APPSTORE_PRECHECK_CONFIG=/nonexistent PRECHECK_VERSION=scorecard bash "$SCAN" --format json 2>/dev/null \
             | jq -r '.findings[]|select(.severity!="PASS" and .suppressed==false)|.rule_id' | sort -u)"
    rm -rf "$tmp"
    want="$(jq -r --arg n "$name" '.[$n].expect_fire[]?' "$SYN")"
    absent="$(jq -r --arg n "$name" '.[$n].expect_absent[]?' "$SYN")"
    for rid in $want; do
      if printf '%s\n' "$fired" | grep -qxF "$rid"; then tp=$((tp+1)); else fn=$((fn+1)); fi
    done
    for rid in $absent; do
      if printf '%s\n' "$fired" | grep -qxF "$rid"; then fp=$((fp+1)); fi
    done
  done
  SYN_TP=$tp; SYN_FP=$fp; SYN_FN=$fn
}

render_card() {
  run_synthetic
  local m; m="$(_metrics "$SYN_TP" "$SYN_FP" "$SYN_FN")"
  local prec="${m#precision=}"; prec="${prec%% *}"
  cat <<EOF
# appstore-precheck — Validation Scorecard

_Generated by \`scripts/scorecard.sh\`. Do not edit by hand._

## Methodology

Two corpora measure two different things:

- **Synthetic** (\`corpus/synthetic/\`): the project's own fixtures, each labelled with the
  rule-ids it is designed to trip (\`expect_fire\`) and rule-ids that must stay silent
  (\`expect_absent\`). Measures **intended-behaviour fidelity**.
- **Real panel** (\`corpus/real/\`): permissively-licensed open-source iOS / React-Native apps
  pinned to a commit, with a one-time human TP/FP labelling pass. Measures **real-code
  false-positive rate**. Run with \`scorecard.sh --real\`.

## Synthetic aggregate

| metric | value |
|---|---|
| true positives  | $SYN_TP |
| false positives | $SYN_FP |
| false negatives | $SYN_FN |
| **precision**   | $prec |

## Honesty

Synthetic measures intended-behaviour fidelity. Real-panel precision measures the
false-positive rate on real open-source code. **Neither claims agreement with
Apple's actual review decisions.** Recall is bounded by labelled known issues and is
not exhaustive.
EOF
}

case "${1:-}" in
  --check)
    tmp="$(mktemp)"; render_card > "$tmp"
    if ! diff -q "$tmp" "$CARD" >/dev/null 2>&1; then
      echo "scorecard: docs/scorecard.md is stale — run scripts/scorecard.sh" >&2
      diff "$CARD" "$tmp" >&2 || true; rm -f "$tmp"; exit 1
    fi
    rm -f "$tmp"
    run_synthetic
    prec="$(_metrics "$SYN_TP" "$SYN_FP" "$SYN_FN")"; prec="${prec#precision=}"; prec="${prec%% *}"
    awk -v p="$prec" -v f="$FLOOR" 'BEGIN{exit !(p+0 >= f+0)}' || {
      echo "scorecard: synthetic precision $prec below floor $FLOOR" >&2; exit 1; }
    echo "scorecard: up to date (precision $prec >= $FLOOR)"
    ;;
  --real)
    bash "$ROOT/scripts/scorecard-real.sh" ;;   # created in Task 5
  ""|--write)
    render_card > "$CARD"; echo "scorecard: wrote $CARD" ;;
  *) echo "scorecard.sh: unknown arg '$1'" >&2; exit 64 ;;
esac
